// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1btaJ5yCFN6eLw73Q6ikxRUHeD_-dL1c',
    appId: '1:1097523035274:web:35a4cdf1695269752e8173',
    messagingSenderId: '1097523035274',
    projectId: 'notesbutbetterflutter',
    authDomain: 'notesbutbetterflutter.firebaseapp.com',
    storageBucket: 'notesbutbetterflutter.appspot.com',
    measurementId: 'G-H4FBNBGXBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhToZeXBVLiYAEYab2iCs5nBsoK1iDkE8',
    appId: '1:1097523035274:android:3217822f963a848b2e8173',
    messagingSenderId: '1097523035274',
    projectId: 'notesbutbetterflutter',
    storageBucket: 'notesbutbetterflutter.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1btaJ5yCFN6eLw73Q6ikxRUHeD_-dL1c',
    appId: '1:1097523035274:web:5ae933f3687a77f02e8173',
    messagingSenderId: '1097523035274',
    projectId: 'notesbutbetterflutter',
    authDomain: 'notesbutbetterflutter.firebaseapp.com',
    storageBucket: 'notesbutbetterflutter.appspot.com',
    measurementId: 'G-1D5WTTMMVB',
  );
}
